name: webdev
description: A tool for web development with Dart.
version: 0.0.2
homepage: https://github.com/devoncarew/webdev
author: Devon Carew <devoncarew@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  analysis_server_lib: ^0.1.0
  args: ^0.13.0
  cli_util: ^0.1.0
  path: ^1.4.0
  stagehand: 1.1.3
  watcher: ^0.9.0
  webkit_inspection_protocol: ^0.3.1

dev_dependencies:
  test: ^0.12.0
